### ISSUE TITLE
Smoother liftover for working with ranges in different genome builds

### ISSUE THREAD

**Issue by mikelove** [nahid18/easylift#1]
Improve liftover operation for working with GRanges. This probably should live in a new package, maybe *easylift*? I'd be happy to work with someone interested in writing their first Bioconductor package.

Currently the operations are:

- Find chain file on UCSC website
- Download
- Unzip
- `rtracklayer::import`
- `rtracklayer::liftOver`
- `unlist`
- `genome()<-` (what about seqinfo/seqlengths?)

From Herve (on tech-advisory-board channel)

"With this improvement to getChromInfoFromUCSC(), the standard way to set the Seqinfo on the lifted object becomes:"

```
to_seqinfo <- getChromInfoFromUCSC("hg19", assembled.molecules.only=TRUE, as.Seqinfo=TRUE)
lifted_seqlevels <- seqlevels(cur)[genome(cur) %in% "hg38"]
seqinfo(cur19) <- update(seqinfo(cur19), to_seqinfo[lifted_seqlevels])
```

with the relevant commit to GenomeInfoDb:

https://github.com/Bioconductor/GenomeInfoDb/commit/345f22c55b8c431f1cf8080af3235f78266ade9c

**Comment by mikelove** [comment]
I created this Issue to link the repo to the Tidyomics Open Challenges project.

I archived the original issue

**Comment by stemangiola** [comment]
FYI in github you can transfer issues from one repo to another.

**Comment by mikelove** [comment]
This is great, and already looks very useful. 

I have a few notes/suggestions:

* if the incoming object has no seqinfo (besides genome), then the outgoing object only has seqinfo on the seqnames that are represented by ranges in `gr`. I think it would be preferable to output the comprehensive seqinfo (`to_genome_info`) in this case
* maybe you can test if the `chain` is gzipped, and if so unzip it for the user, see `file_ext` and `unzip`
* going further, it would be cool to have the ability for user not to specify `chain` if there exists a file already in BiocFileCache, see below for example:

```
# the user should do these steps manually, e.g. downloading the chain file, and adding to BFC:
library(BiocFileCache)
bfc <- BiocFileCache()
bfcadd(bfc, "hg19ToHg38.over.chain", "/path/to/hg19ToHg38.over.chain")
# now your function could use the following steps to retrieve a previously cached resource:
q <- bfcquery(bfc, "hg19ToHg38.over.chain")
nrow(q)
q$rid
bfc[[q$rid]]
import(bfc[[q$rid]])
```

**Comment by nahid18** [comment]
> This is great, and already looks very useful.
> 
> I have a few notes/suggestions:
> 
> * if the incoming object has no seqinfo (besides genome), then the outgoing object only has seqinfo on the seqnames that are represented by ranges in `gr`. I think it would be preferable to output the comprehensive seqinfo (`to_genome_info`) in this case
> * maybe you can test if the `chain` is gzipped, and if so unzip it for the user, see `file_ext` and `unzip`
> * going further, it would be cool to have the ability for user not to specify `chain` if there exists a file already in BiocFileCache, see below for example:
> 
> ```
> # the user should do these steps manually, e.g. downloading the chain file, and adding to BFC:
> library(BiocFileCache)
> bfc <- BiocFileCache()
> bfcadd(bfc, "hg19ToHg38.over.chain", "/path/to/hg19ToHg38.over.chain")
> # now your function could use the following steps to retrieve a previously cached resource:
> q <- bfcquery(bfc, "hg19ToHg38.over.chain")
> nrow(q)
> q$rid
> bfc[[q$rid]]
> import(bfc[[q$rid]])
> ```

Thank you for the suggestions. I have pushed code for the `.gz` file support.

`if the incoming object has no seqinfo (besides genome)`
Can you kindly provide the `gr` for such an object in the context of the code below? Thank you so much!

```
gr <- GRanges(seqname = Rle(paste("chr", 1, sep = "")),
              ranges = IRanges(start = 1, end = 200000))
genome(gr) <- "hg19"
to <- "hg38"
chain <- "data/hg19ToHg38.over.chain.gz"
lifted <- easylift(gr, to, chain)
```

**Comment by mikelove** [comment]
will review and provide an example soon

**Comment by mikelove** [comment]
Your current example gives:

```
!> seqinfo(lifted)
 Seqinfo object with 2 sequences from hg38 genome:
   seqnames seqlengths isCircular genome
   chr1      248956422      FALSE   hg38
   chr19      58617616      FALSE   hg38
```

I think it should just return the complete seqinfo.

I'll push a suggested change in one minute.

**Comment by mikelove** [comment]
I think this is right actually [34777ce](https://github.com/nahid18/easylift/commit/34777ce6e93e9eb39dc5805ee06d7ba48eb613a6)

...its different than the original suggestion, but I think the original suggestion wasn't correct. It doesn't make sense to only update the sequences with ranges represented in `gr`, because you end up with a mix of different builds. We should just replace the entire set of sequences with `to_seqinfo`.

**Comment by mikelove** [comment]
Idea: you could maybe now start moving this function into a Bioconductor package using `biocthis`. That is, this repo will become an R package, let me know if you have any questions about the mechanics of this. You are aiming for the root of the repository to become the root of the package, e.g. the location with the `DESCRIPTION` file. See `biocthis` for the basics of making a package skeleton appropriate for Bioc.

I can give some assistance afterward with the BiocFileCache idea.

**Comment by nahid18** [comment]
@mikelove awesome! thank you so much for the push. I will turn this into a package using `biocthis`

**Comment by nahid18** [comment]
@mikelove package development initiated and it builds properly. Can be installed and used as intended. Just tried the code below and it works:

```
BiocManager::install("nahid18/easylift")
BiocManager::install("GenomicRanges")

library("easylift")
library("GenomicRanges")

gr <- GenomicRanges::GRanges(seqname = Rle(paste("chr", 1, sep = "")),
              ranges = IRanges(start = 1, end = 200000))
genome(gr) <- "hg19"
to <- "hg38"
chain <- "hg19ToHg38.over.chain.gz"

lifted <- easylift(gr, to, chain)

seqinfo(gr)
seqinfo(lifted)
```

**Comment by mikelove** [comment]
Great! I’ll take a look soon

**Comment by mikelove** [comment]
I just took a shot at adding BiocFileCache support, wanna try it?

**Comment by mikelove** [comment]
Kind of magical

```
> gr |> easylift("hg38") # chr5:1e6-2e6, hg19
GRanges object with 2 ranges and 0 metadata columns:
      seqnames          ranges strand
         <Rle>       <IRanges>  <Rle>
  [1]     chr5  999885-1785328      *
  [2]     chr5 1785330-1999886      *
  -------
  seqinfo: 25 sequences (1 circular) from hg38 genome
```

**Comment by nahid18** [comment]
> Kind of magical
> 
> ```
> > gr |> easylift("hg38") # chr5:1e6-2e6, hg19
> GRanges object with 2 ranges and 0 metadata columns:
>       seqnames          ranges strand
>          <Rle>       <IRanges>  <Rle>
>   [1]     chr5  999885-1785328      *
>   [2]     chr5 1785330-1999886      *
>   -------
>   seqinfo: 25 sequences (1 circular) from hg38 genome
> ```

wow! this is indead magical! thank you so much! @mikelove

**Comment by stemangiola** [comment]
@nahid18  please add your authorship details here https://docs.google.com/spreadsheets/d/19XqhN3xAMekCJ-esAolzoWT6fttruSEermjIsrOFcoo/edit?usp=sharing

**Comment by nahid18** [comment]
@mikelove Submitted the package to Bioconductor: https://github.com/Bioconductor/Contributions/issues/3122

**Comment by mikelove** [comment]
Nice! 🎉 

Open issue to first R package in a few weeks.
